server:
  port: 8088

dubbo:
  application:
    name: dubbo-consumer  # 应用名称
    #owner: aggerChen      # 应用所属者
    #organization: agger   # 应用所属组织
  registry:
    #id: zookeeper-registry #注册中心id
    #protocol: zookeeper    #注册中心协议
    #address: zookeeper://127.0.0.1:2181 #注册中心地址
    address: N/A
  #monitor:
    #protocol: registry # 注册监控中心
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
data:
  elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: localhost:9300
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis